import { Inter } from "next/font/google";
import { AuthProvider } from "@/components/auth";
import Header from "@/components/layout/Header";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
      <html lang="en" suppressHydrationWarning>
        <AuthProvider>
          <body><Header />{children}</body>
        </AuthProvider>
      </html>
  );
}
